version: 2.1
orbs:
  helm: circleci/helm@3.1.0

jobs:
  install_chart:
    docker:
      - image: cimg/python:3.8
    resource_class: small
    steps:
      - helm/install-helm-client
      - run:
          name: Install Helm chart
          command: |
            helm install my-release .

workflows:
  start-run: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - install_chart
