name: CI
run-name: Trigger by @${{ github.actor }}

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        required: true
        type: string

jobs:
    sample:
      environment:
        name: staging_environment
        url: https://github.com
      name: Sample Job
      runs-on: ubuntu-latest
      steps:
        - name: Print the input name to STDOUT
          run: echo The username is ${{ inputs.username }}
    # publish_helm:
    #     name: Publish Helm Chart
    #     runs-on: ubuntu-24.04
    #     permissions:
    #         attestations: write
    #         contents: read
    #         packages: write

    #     steps:
    #     - name: "Checkout repository"
    #       uses: actions/checkout@v4
    #     - name: "Set up Helm"
    #       uses: azure/setup-helm@v4.2.0
    #     - name: "Login to Github OCI"
    #       uses: docker/login-action@v2
    #       with:
    #         registry: ghcr.io
    #         username: ${{ github.actor }}
    #         password: ${{ secrets.GITHUB_TOKEN }}
    #     - name: "Package Helm Chart"
    #       run: |
    #         helm package .
    #     - name: "Publish Helm Chart"
    #       run: |
    #         helm push *.tgz oci://ghcr.io/${{ github.repository_owner }}/wordpress
