name: CI

on:
  push:
    branches:
      - main

jobs:
    upgrade_helm:
        name: Upgrade Helm Chart
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: "Checkout repository"
          run: echo "Checking out repository"
        - name: "Upgrade Helm Chart"
          uses: wahyd4/kubectl-helm-action@master
          env:
            KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          with:
            args: |
                kubectl cluster-info && \
                helm upgrade --install wordpress-basic . --wait && \
                kubectl rollout status deployment/wordpress-basic
